export enum QueryKeys {
  userInfo = 'userInfo',
  uncommissionedSites = 'uncommissionedSites',
  modules = 'modules',
  moduleFields = 'moduleFields',
  strings = 'strings',
  stringDetails = 'stringDetails',
  inverters = 'inverters',
  inverterModels = 'inverterModels',
  inverterDetails = 'inverterDetails',
  files = 'files',
  unattachedGateways = 'unattachedGateways',
  editedSite = 'editedSite',
  meterVerificationGuide = 'meterVerificationGuide',
  batteryVerificationGuide = 'meterVerificationGuide',
  inverterVerificationGuide = 'meterVerificationGuide',
  batteryModels = 'batteryModels',
  meter = 'meter',
  meterModels = 'meterModels'
}
