import React from "react";
import { Meta, Story } from "@storybook/react";
import { Typography } from 'ui/typography/Typography';

export default {
    component: Typography,
    title: 'Components/Typography',
    // TODO: these should be autogenerated, but we get nothing if I don't explicitly configure it
    argTypes: {
        variant: {
          options: ['h1', 'h2', 'h3', 'body'],
          control: { type: 'select' },
        },
      },
} as Meta;

const Template: Story = (args) => <Typography {...args} className="storybook-styles-debug-test ui-styles-debug-test">This is some cool text</Typography>;

export const H1 = Template.bind({
    variant: 'h1',
    className: 'asd'
});
export const H2 = Template.bind({
    variant: 'h2'
});
